### ISSUE TITLE
Install fedora-messaging locally and publish a test message

### ISSUE THREAD

**Issue by justwheel** [fedora-infra/badgr-server#1]
# Summary

[Install `fedora-messaging`](https://fedora-messaging.readthedocs.io/en/stable/tutorial/installation.html) and [publish a test message](https://fedora-messaging.readthedocs.io/en/stable/publishing.html)

# Background

`fedora-messaging` is like a live feed of the Fedora Project. Different kinds of contribution activities are registered in the `fedora-messaging` bus. This allows an application to publish a message that triggers an application somewhere else in Fedora, like awarding a new [Fedora Badge](https://docs.fedoraproject.org/en-US/badges/).

`fedora-badges` receives and publishes messages to the Fedora Infrastructure `fedora-messaging` bus. Understanding how `fedora-messaging` works is useful to understand for future development work.

# Details

Complete the following steps:

* [Install fedora-messaging](https://fedora-messaging.readthedocs.io/en/stable/installation.html) on your device
* [Set up fedora-messaging in new test project](https://fedora-messaging.readthedocs.io/en/stable/tutorial/installation.html)
* Write script to [publish a test message](https://fedora-messaging.readthedocs.io/en/stable/publishing.html)

Use the [fedora-messaging documentation](https://fedora-messaging.readthedocs.io/en/stable/index.html) for guidance. You can post a screenshot of running your test script here in the ticket when you're done! :computer: :camera: 

# Outcome

* Working `fedora-messaging` installation
* Successful understanding how to publish a message to `fedora-messaging` bus

---

_Note_: This issue will remain open until the end of the Outreachy 2020 application phase. This ticket does not require an assignee to work on this task – it can be repeated by anyone.

**Comment by sukkubm** [comment]
Hi @jwflory , 
I am an Outreachy intern aspirant for 2020. I have installed fedora-messaging and have configured new project. When I run the following script, I am not getting any error. 
```PYTHON
from fedora_messaging import api, message
msg = message.Message(topic=u'nice.message', headers={u'niceness': u'very'},
                      body={u'encouragement': u"You're doing great!"})
api.publish(msg)
```
How do I verify if the message was sent successfully? I am not able to see any changes in RabbitMQ admin http://localhost:15672/.

The `config.toml` looks something like this -
```toml
# A sample configuration for fedora-messaging. This file is in the TOML format.
amqp_url = "amqp://"
#callback = "fedora_messaging.example:printer"
passive_declares = false
publish_exchange = "amq.topic"
topic_prefix = ""

[tls]
ca_cert = "/etc/fedora-messaging/cacert.pem"
keyfile = "/etc/fedora-messaging/fedora-key.pem"
certfile = "/etc/fedora-messaging/fedora-cert.pem"

[client_properties]
app = "Fedora Messaging tutorial"

# If the exchange or queue name  has a "." in it, use quotes as seen here.
#[exchanges."amq.topic"]
#type = "topic"
#durable = true
#auto_delete = false
#arguments = {}

#[queues.my_queue]
#durable = true
#auto_delete = false
#exclusive = false
#arguments = {}

# Note the double brackets below. To add another binding, add another
# [[bindings]] section. To use multiple routing keys, just expand the list here.
#[[bindings]]
#queue = "my_queue"
#exchange = "amq.topic"
#routing_keys = ["#"]

[consumer_config]
example_key = "for my consumer"

[qos]
prefetch_size = 0
prefetch_count = 25

[log_config]
version = 1
disable_existing_loggers = true

[log_config.formatters.simple]
format = "[%(levelname)s %(name)s] %(message)s"

[log_config.handlers.console]
class = "logging.StreamHandler"
formatter = "simple"
stream = "ext://sys.stdout"

[log_config.loggers.fedora_messaging]
level = "INFO"
propagate = false
handlers = ["console"]

# Twisted is the asynchronous framework that manages the TCP/TLS connection, as well
# as the consumer event loop. When debugging you may want to lower this log level.
[log_config.loggers.twisted]
level = "INFO"
propagate = false
handlers = ["console"]

# Pika is the underlying AMQP client library. When debugging you may want to
# lower this log level.
[log_config.loggers.pika]
level = "WARNING"
propagate = false
handlers = ["console"]

[log_config.root]
level = "ERROR"
handlers = ["console"]
```
